### ISSUE TITLE
Streaming encryption/decryption of jpg file 34,469 bytes fails to yield correct plaintext

### ISSUE THREAD

**Issue by tomtitchener** [RNCryptor/rncryptor-hs#15]
![31950](https://cloud.githubusercontent.com/assets/5193989/18920216/b5de6714-856e-11e6-8894-bb2c279f3be7.jpg)
![34469](https://cloud.githubusercontent.com/assets/5193989/18920246/cd0b3278-856e-11e6-98da-eb5ce4e555e9.jpg)

(see bottom for solution!)

utilities rncryptor-encrypt and rncryptor-decrypt succeed (show no error), but comparison of plaintext before and after does not succeed for a JPG file with 34,469 bytes and for other JPG files larger than 34,469 bytes:

```
bash-3.2$ cat 34469.jpg | rncryptor-encrypt secret > foo.jpg.enc
bash-3.2$ cat foo.jpg.enc | rncryptor-decrypt secret > foo.jpg
bash-3.2$ cmp 34469.jpg foo.jpg
34469.jpg foo.jpg differ: char 32753, line 177
```

However, the same sequence does succeed for a JPG file size 31,950 bytes, and for other JPG files smaller smaller than 31,950 bytes:

```
bash-3.2$ ls -l 31950.jpg
-rw-r--r-- 1 tom_titchener staff 31950 Sep 28 11:13 31950.jpg
bash-3.2$ cat 31950.jpg | rncryptor-encrypt secret > foo.jpg.enc
bash-3.2$ cat foo.jpg.enc | rncryptor-decrypt secret > foo.jpg
bash-3.2$ cmp 31950.jpg foo.jpg
```

When the plaintexts do not cmp, they almost always differ starting at byte 32,753, infrequently starting at byte 32,754.

```
bash-3.2$ cmp -l 34469.jpg foo.jpg
32753 145  12
32754 121  25
32755 166 104
32756  66 366
32757 241 232
32758  45 255
32759 247 136
32760 311 312
32761 121 337
32762 350 271
32763 213 221
32764 370 224
32765 115  64
32766 115 367
32767   5 313
32768  12 320
```

If I put a bit of tracing that logs stream writes, I can see the difference is the file that works just writes from the "finalizer" function:

```
bash-3.2$ cat 31950.jpg | rncryptor-encrypt secret > foo.jpg.enc
encryptStream writing header 34 bytes
Finalize writing 31952 bytes
bash-3.2$ cat foo.jpg.enc | rncryptor-decrypt secret > foo.jpg
Finalize writing 31950 bytes
```

Whereas the file that fails also pumps a single block out from processStream:

```
bash-3.2$ cat 34469.jpg | rncryptor-encrypt secret > foo.jpg.enc
encryptStream writing header 34 bytes
Block writing 32752 bytes
Finalize writing 1728 bytes
bash-3.2$ cat foo.jpg.enc | rncryptor-decrypt secret > foo.jpg
Block writing 32704 bytes
Finalize writing 1765 bytes
```

So it looks like there's something funky going on with the integration of writing in processStream with finalize processing in Decrypt.hs, maybe?

Given the HMAC computes on decrypt, I'm assuming the problem comes on that side ...

Figured it out!  As the nice comment below says, initialize the IV to the cipher text.
But the code originally said 

```
      in (ctx { ctxHeader = newHeader, ctxHMACCtx = newHmacCtx }, clearText)
```

```
--------------------------------------------------------------------------------
-- | Encrypt a raw Bytestring block. The function returns the encrypt text block
-- plus a new 'RNCryptorContext', which is needed because the IV needs to be
-- set to the last 16 bytes of the previous cipher text. (Thanks to Rob Napier
-- for the insight).
encryptBlock :: RNCryptorContext
             -> ByteString
             -> (RNCryptorContext, ByteString)
encryptBlock ctx clearText = 
  let cipherText = encryptBytes (ctxCipher ctx) (rncIV . ctxHeader $ ctx) clearText
      !newHmacCtx = update (ctxHMACCtx ctx) cipherText
      !sz         = B.length clearText
      !newHeader  = (ctxHeader ctx) { rncIV = B.drop (sz - 16) cipherText }
      in (ctx { ctxHeader = newHeader, ctxHMACCtx = newHmacCtx }, cipherText)
```

Making the change above from "clearText" to "cipherText" fixes the problem.

```
bash-3.2$ cat 34469.jpg | rncryptor-encrypt secret > foo.jpg.enc
encryptStream writing header 34 bytes
Block writing 32752 bytes
Finalize writing 1728 bytes
bash-3.2$ cat foo.jpg.enc | rncryptor-decrypt secret > foo.jpg
Block writing 32704 bytes
Finalize writing 1765 bytes
bash-3.2$ cmp 34469.jpg foo.jpg
```

**Comment by adinapoli** [comment]
Excellent detective job, @tomtitchener !

Shout if you think we can close this (as I have merged your PR).

**Comment by tomtitchener** [comment]
Thanks, @adinapoli!  

RE: closing, it's easy to confirm encrypt and decrypt on MacOS are symmetric.

What I'm waiting for is to confirm encrypt on Haskell/MacOS is symmetric with decrypt on Swift/iOS.

I'm a little worried about this.  

Despite staring at the Haskell and Swift code for quite a while, I don't follow how the chunking works.

I see the need to reinitialize the IV on encrypt/decrypt of every block.  

But it seems to me the size of the block in the Haskell code is going to depend on buffering in System.IO.stdin.

And I can't even *find* the update to the IV in the Swift code!

Maybe @rnapier could help out here...

I worry there could be the same kind of asymmetry between Haskell/MacOS and Swift/IOS for encrypt/decrypt of large amounts of data ...

Without a fixed block size, how would the decrypt ever know where to reinitialize that IV?

Any ideas?  Probably I've just overlooked something. 

I'll post when I hear from the guys on our team doing the Swift/iOS decryption.

**Comment by adinapoli** [comment]
Hey @tomtitchener , my answer will sound extremely naive, so I guess it's better to wait for what Rob has to say. What I can tell you is that the update cycle (where the `IV` vector is involved) is needed in a streaming setting to make the whole thing work. My story goes as follow: our iOS developer decided we needed to encrypt/decrypt large quantities of data (specifically, videos) and picked `RNCryptor` as the crypto library, but obviously I needed to decrypt the data on the Haskell server and due to the fact there were no library available, I had to wrote my own.

After implementing an initial poc following the V3 spec, I tried to decode a sample video only to find that _it almost worked_: it had nasty artifacts every now and then (think like when you have a delay in broadcasting a real time video). I wrote to Rob which after quickly analysing the problem found the culprit as being the fact I was not reinitialising the IV. Once I did that, it worked.

I cannot speak for the "new" library version (namely the version we rolled out with the revised work on the HMAC), but I can speak for the "old" one, which is now serving more than 1000 videos per day none of which comes out corrupted due to a bad encrypt/decrypt cycle. Every time I did a "diff" at the binary level between the original video and the one decrypted on the Haskell side they came out identical.

This is of course totally empirical and not a very satisfying answer, but more an experience report about how that worked out for us. I'm very interested in the concerns you raise, but I'm afraid not to have the technical depth required to answer you, so that's about it 😉 

Certainly what could help is more and more tests; non only add the reference test vectors but also this kind of "interlanguage" roundtrips, which is probably the best way to improve our confidence in the library and spot bugs !

**Comment by tomtitchener** [comment]
I don't think your answer is naive, @adinapoli!  Better yet, I think it matches my experience with stream encryption.  The failure mode before the latest PR that you merged is _exactly_ what you described before you added the fix to re-initialize the IV.  Decryption succeeded, but the result had errors, in this case corruptions in the JPG file.  The latest PR fixes that problem just like you describe fixing the problem earlier by re-initializing the IV.  BTW, I suspect I inadvertently created this bug during one of my initial patches to your library, sorry!  The way I currently use the RNCryptor-hs library is to encrypt all the multimedia files, then to immediately decrypt them and validate output compares exactly with the input.  Which it does, specifically even for large files where the corruption happened before, but doesn't any more.  Moreover, I think I now understand how this works between Haskell and Swift.  Well enough, at any rate, to mark this issue closed.  Thanks for you help!

**Comment by adinapoli** [comment]
No problem @tomtitchener ! Please keep your questions and your PRs coming, they are always very appreciated! 😉

**Comment by rnapier** [comment]
>And I can't even find the update to the IV in the Swift code!

Just to shed a little more light here for future work, and to confirm and expand what you've already worked out:

The AES algorithm encrypts exactly 16 bytes of plaintext into 16 bytes of ciphertext. It does nothing else. In order to encrypt more (or technically less), you need a "mode" and RNCryptor uses CBC. CBC chains together 16 byte blocks, mixing them with the output of the previous block's encryption. This destroys patterns in the ciphertext that would otherwise emerge. Since each block depends on the encryption of the block before, there is the question of what to mix with block 0. That's the IV. It is logically the "encryption of an imaginary block -1" and is, when correctly implemented, random. Since it's random, it has to be passed along in the format so the decryptor can initialize to the right state.

OK, so where does the Swift code keep track of "the output of the previous block's encryption?" Inside the low-level call to CCCryptorUpdate. CCCryptor structures are stateful and keep track of this for you. In Haskell, this state has to be externalized and returned.

Some points:

* You cannot decrypt a partial block. This seems to be the problem you were running into. I suspect 32,753 is related to some buffer size (it's 32k-15, so there is probably a 32k buffer somewhere). Somewhere there are buffers that interact such a way that when you get to that many bytes you wind up with a block that isn't exactly a multiple of 16. the fact that it is occasionally 32,754 instead is probably luck. You would expect to get the right value by chance about 0.5% of the time (1/255).

* In Swift, CCCryptorUpdate automatically handles this condition in a way not unlike to the Decryptor.update method in RNCryptor. If it doesn't have the right amount of data yet, it sticks it in a buffer for next time it's called.

**Comment by tomtitchener** [comment]
Cool, @rnapier!  Thanks for the very thorough summary.  This has been a _great_ library, and it's been a real pleasure to have the chance to work on the Haskell side of the fence, with valuable help from @adinapoli.
