### ISSUE TITLE
Detect incorrect password?

### ISSUE THREAD

**Issue by timbod7** [RNCryptor/rncryptor-hs#18]
Thanks for the library!

I am using rncryptor-hs for this project: https://github.com/timbod7/secretfs

Currently, if the incorrect keyphrase is provided, then there is no error in decryption, the call to `decrypt` results in meaningless data.  Is that the intended behaviour? Under what circumstances is it expected to throw a InvalidHMACException?

**Comment by adinapoli** [comment]
Hey Tim!

> I am using rncryptor-hs for this project: https://github.com/timbod7/secretfs

Yea, I saw the announcement on `/r/haskell`, very cool stuff indeed!

> Is that the intended behaviour? Under what circumstances is it expected to throw a InvalidHMACException?

Currently the error handling story is a bit fragile, I'd admit. If you see the only circumstance where we throw an error is here:

https://github.com/RNCryptor/rncryptor-hs/blob/master/src/Crypto/RNCryptor/V3/Decrypt.hs#L149

So in theory that happens if the two HMAC (the computed and the original one) are not equal ( @tomtitchener wrote that part of the function, so maybe he can help you with more insights 😉  ).

Orthogonally, I feel that throwing an error in a pure function is arguably not the right thing to do (or, it's not everybody cup of tea), so we could look at having a `decryptEither` function which would return a `Either DecryptionError ByteString` and implement `decrypt` using `decryptEither` under the hood, so we don't break backward compatibility.

As regards to "intended" behaviour, I honestly cannot comment (but maybe @rnapier can): my gut feeling is that usually when decrypting junk input data you should get junk output as a result, but this could be totally my naive view of cryptography 😀  I'm sure Rob can tell us a bit more!

Alfredo

**Comment by rnapier** [comment]
rncryptor-hs is incorrect in that it doesn't check the HMAC result. Failure
to check HMAC is a violation of the spec (it won't pass the test vectors in
the RNCryptor-Spec repo). But even if it did, it's impossible to
distinguish between incorrect password and message corruption. While there
are security arguments that this is a feature, it was not the intent of the
format. It's just a consequence of the design. I've long talked about
rolling a v4 format (also discussed in the RNCryptor-Spec repo) that
addresses this (and, just as importantly, let's you check for a bad
password without fully decrypting the entire message), but it's not fixable
in the v3 format.

**Comment by tomtitchener** [comment]
@timbod7, have you tried cloning and using this library, say vs. using the one on Hackage?
With help from @adinapoli and @rnapier, I was able to add hmac validation to the current version of the library.  I just validated decryption with the wrong key using the current version of this library yields an HMAC error (see below).  So I wonder if maybe your problem goes away if you use the current version?

```
bash-3.2$ cat README.md | /Users/tom_titchener/Documents/Dev/Haskell/rncryptor-hs/.stack-work/install/x86_64-osx/lts-6.5/7.10.3/bin/rncryptor-encrypt secret > README.md.enc
bash-3.2$ cat README.md.enc | /Users/tom_titchener/Documents/Dev/Haskell/rncryptor-hs/.stack-work/install/x86_64-osx/lts-6.5/7.10.3/bin/rncryptor-decrypt secret > README.md.decr
bash-3.2$ diff README.md README.md.decr 
bash-3.2$ rm README.md.decr
bash-3.2$ cat README.md.enc | /Users/tom_titchener/Documents/Dev/Haskell/rncryptor-hs/.stack-work/install/x86_64-osx/lts-6.5/7.10.3/bin/rncryptor-decrypt bad > README.md.decr
rncryptor-decrypt: InvalidHMACException: Untrusted HMAC was [245,179,111,85,239,119,101,36,240,218,244,54,70,78,227,254,130,136,237,93,66,29,175,39,74,197,150,99,47,205,179,82], but the computed one is [192,31,160,161,95,153,30,142,44,33,112,25,14,16,81,244,71,221,84,71,36,11,68,139,38,90,49,156,224,1,182,136].

```

**Comment by adinapoli** [comment]
> rncryptor-hs is incorrect in that it doesn't check the HMAC result. Failure
to check HMAC is a violation of the spec

@rnapier I swear one day I will fix this -- I'm putting my trust in the xmas break... or in the 2017 resolutions 😉  😀

**Comment by timbod7** [comment]
@tomtitchener - thanks for the pointer. I was looking at the hmac validation code in the repo, and assuming it was present in the most recent release on hackage. With the most recent committed version,  an incorrect password now results in a failed hmac validation.

I'd much prefer it if the type of `decrypt` reflected the potential for failure. @adinapoli - would you accept a PR that changed the signature of `decrypt` to either

```
decrypt :: ByteString -> ByteString -> Maybe ByteString
```

or

```
decrypt :: ByteString -> ByteString -> Either RNCryptorException ByteString
```

**Comment by adinapoli** [comment]
> I'd much prefer it if the type of decrypt reflected the potential for failure. @adinapoli - would you accept a PR

Absolutely Tim, although there is an API design question to be answered here, as both functions (`decrypt` and `decryptEither`) have a fit inside a library. For example the (arguably opinionated) choice of [Cryptonite](http://hackage.haskell.org/package/cryptonite-0.20/docs/Crypto-Tutorial.html) is to expose simply a `decrypt` function which has the same signature as this one, with the same caveats. I think that for an Haskell user using these libraries it could be a good thing to not have the cognitive overload to have 2 different APIs, but with the added benefit to be able to "opt-in" into a safer decrypt with `decryptEither`.

For this reason, unless you guys have strong sentiment against, I propose we add a `decryptEither :: ByteString -> ByteString -> Either RNCryptorException ByteString` function and we rewrite `decrypt` as using `decryptEither` internally, but without breaking the API. Finally, we release `0.2.0.0` as per pvp/semver (we introduced a new function, without breaking backwards compat).

What do you guys think? Am I making sense?

**Comment by timbod7** [comment]
I'd generally prefer to avoid partial functions like `decrypt` in it's current form. I'm not sure that your cryptonite reference is appropriate here - the link is to demo code (where use of `error` is reasonable) and not the library code itself.

Having said that, as long as there is a total function available like `decryptEither`, I'm happy. So I'll put together a PR along those lines.

**Comment by adinapoli** [comment]
> I'd generally prefer to avoid partial functions like decrypt in it's current form.

I prefer too, but I also try to balance pragmatism with safety from times to time. I think that as long as the end user knows the consequences of using such pure function in the code, we should be fine (a bit like the `head` vs `headMay` controversy, which we could be discussing ad infinitum 😜  ). I'm also very happy to revisit this as we go along, merely slowly deprecating `decrypt` in favour of `decryptEither` and rename the two functions when `1.0.0` lands, so that the end user will only need to use interchangeably `decrypt` or `decryptEither`.

> I'm not sure that your cryptonite reference is appropriate here - the link is to demo code

From a quick skim to the source code it seems more of a design decision -- there are functions like `decryptSafer` which returns an `Either` but the majority seems to operate as pure, non-total functions (but maybe I'm simply undercaffeinated and thus wrong).

In any case, I guess enough bike shedding! We can take things from there 😄

**Comment by timbod7** [comment]
Thanks - all good now.
